# Generated by Django 4.0.5 on 2022-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_ph',
            field=models.ImageField(null=True, upload_to='media/prof/<django.db.models.fields.CharField>/'),
        ),
    ]
