# Generated by Django 4.0.5 on 2022-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255, null=True, unique=True)),
                ('join', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
            ],
        ),
    ]
