# Generated by Django 4.0.5 on 2022-07-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author_delete_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogUser',
        ),
    ]
