# Generated by Django 4.0.5 on 2022-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_bloguser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./files/profile/'),
        ),
    ]
