# Generated by Django 4.0.5 on 2022-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_bloguser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(null=True, upload_to='files/profile/'),
        ),
    ]
