# Generated by Django 4.0.5 on 2022-07-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_bloguser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
